default_context:
  project_name: 'ShareMate_App'
  project_slug: 'ShareMate'
  domain_main: 'ShareMate.com'
  domain_staging: 'stag.ShareMate.com'
  docker_swarm_stack_name_main: 'ShareMate-com'
  docker_swarm_stack_name_staging: 'stag-ShareMate-com'
  secret_key: 'a5c2bfbbea4d20114917cf475179d8d60fa2d5bb4cbbec3ca37afea9637f3eaf'
  first_superuser: 'admin@ShareMate.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ShareMate.com", "https://stag.ShareMate.com", "https://ShareMate.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@ShareMate.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@ShareMate.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'ShareMate.com'
  traefik_constraint_tag_staging: 'stag.ShareMate.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
